### PR TITLE
Fixed signalOf race condition of initial value + added test to that. Als...

### PR DESCRIPTION
**Pull request by pchlupacek**
...o removed the deprecation on async.signal.

### CODE REVIEW

**Comment by djspiewak** [comment]
I strongly disagree with removing the deprecation.  It doesn't make any sense to have a signal without a value, which is in fact the argument that was made when the deprecation was added in the first place.

**Comment by pchlupacek** [comment]
@djspiewak, @pchiusano  please can you shortly look on this PR? This fixes #347. Also contrary to previous opinion I think we SHALL NOT deprecate `async.signal`. There are use cases where we need it (i.e. `time.awakeEvery`) and I don't see any benefit with replacing this with `async.signalOf[Option[Int]](None).discrete.collect{ case Some(x) =>  x }` although this can be  option as well, if we really really insist on deprecating the `async.signal`. Additionally, I have changed signature of `async.toSignal` from `mutable.Signal` to `immutable.Signal` to prevent race conditions between upstream/downstream mutation of signal. 

If still someone would like to have both in same Signal, wye IMHO has to be used instead. Perhaps, I may came with signal combinators (like wye, merge) in separate PR.

**Comment by pchlupacek** [comment]
@djspiewak thanks on opinion. There is in fact reasoning behind signal that has no value set, and some example is in `time.awakeEvery`. There are some more similar use cases of using signal without value to really signal some sort of `start` of some other computation. 

As mentioned in explanation I was just writing, we can still keep deprecation and replace it with some sort of combinator, perhaps even make the `unset` behaviour some sort of explicit syntax. 

I still think that `unset` signal is easier discoverable than race condition within signal, but, again we perhaps may have both.

**Comment by pchlupacek** [comment]
@djspiewak this is what I did:

- deprecated back `async.signal`
- introduced `async.signalUnset` for explicit `unset` behaviour
- removed `haltOnSource` from `async.toSource`, hence I never saw `async.toSignal` with anything else than setting this to `true` and hence `toSignal` is immutable now, you don't have any other way than terminating the `source` to stop the signal anyhow. 

LMK what do you think.

**Comment by djspiewak** [comment]
LGTM.  I know it's just a name, but `signalUnset` doesn't suggest to the user that this is the "primary" way to get a `Signal`.  So users can go for it if and only if they need the unset behavior.

**Comment by pchlupacek** [comment]
@djspiewak I agree with you that `unexpected` or `important` behaviours shall be explicitly visible to user, and agree that this was confusing on `signal`. Thanks.

**Pull request merged**
