### PR TITLE
FS2: Add process1.awaitOption

### PR DESCRIPTION
**Pull request by fiadliel**
This outputs the first value received from the input, or None.

### CODE REVIEW

**Comment by pchiusano** [comment]
I'm not sure how useful his is, but I'm fine with including it, however please just define in terms of pull1.await1Option.

Also it should be renamed to await1Option.

**Comment by pchiusano** [comment]
Basically any combinator that produces just a single output is more useful returning the output as the result of the Pull, making it easy to use in other pulls.

**Comment by fiadliel** [comment]
Done. I will try and keep that in mind for any future changes...

I also think this is of limited use (it seems to have been mostly used for internal purposes in scalaz-stream), so I wonder if we should just leave it out, process1 is already fairly kitchen-sink-y.

**Comment by pchiusano** [comment]
Yeah, actually you've convinced me, lets just leave it out for now. We can always revisit later.

**Pull request closed without merging**
